PROTON-2330-cpp-link-properties
apache/qpid-proton pull request #293
Opened 2021-01-28 16:49 UTC by pjfawcett

In C++ API, allow setting of link properties via sender and receiver options
Allow query of link properties set by remote end
Add tests

2021-01-28 18:06 UTC, astitcher requested changes

2021-01-28 18:20 UTC, pjfawcett commented on cpp/src/link_test.cpp
> +        connection = c.connect("//:5678");
Will do

2021-01-28 18:27 UTC, pjfawcett commented on cpp/src/link_test.cpp
> + */
I vacillated about which source file was the best home for these tests.  Happy to take your guidance and move them to the container tests.

2021-02-10 13:47 UTC, pjfawcett commented on cpp/src/link_test.cpp
> + */
@astitcher are you happy with the updated tests?

2021-02-10 15:33 UTC, astitcher approved these changes
This looks good - could you create a covering JIRA; squash into a single commit; then edit the commit message to include the JIRA reference (see most of the other commit messages). (This allows us to put together the release notes and to link commits to the issue tracking system)
Then I'll be happy to merge it.

2021-02-11 11:48 UTC, pjfawcett commented
Raised separate, sub-task, JIRA PROTON-2332 to cover just the work on link properties. 
Squashed commits and re-worded commit message to standard format

2021-03-10 09:36 UTC, pjfawcett commented
@astitcher can this be merged now?

2021-03-24 09:59 UTC, merged